# Generated by Django 3.1 on 2022-03-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habr',
        ),
    ]
